apiVersion: ae.dev/v1alpha1
kind: Deployment
metadata:
  name: qdrant
  namespace: ai-fabric-lab
  labels:
    app: qdrant
    workerbee.k1s.dev/project: ai-fabric-lab
spec:
  image: qdrant/qdrant:v1.13.4
  replicas: 1
  ports:
    - name: http
      containerPort: 6333
    - name: grpc
      containerPort: 6334
  service:
    ports:
      - name: http
        port: 6333
        targetPort: 6333
      - name: grpc
        port: 6334
        targetPort: 6334
  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
    limits:
      cpu: 4
      memory: 16Gi
  volumes:
    - hostPath: /srv/storage/k1s/ai-fabric-lab/qdrant
      mountPath: /qdrant/storage
