"""Project-scoped WorkerBee runbook artifact helpers."""

from __future__ import annotations

import json
import shutil
import time
from pathlib import Path
from typing import Any

from workerbee.contract import WorkerBeeError

PROJECT_RUNBOOK_API_VERSION = "workerbee.project-runbook/v1"
DEFAULT_REPO_RUNBOOK_PATH = "docs/workerbee-runbook.md"
RUNBOOK_UPDATE_MODES = {"append", "replace"}


def project_runbook_status(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    git_root: Path | None = None,
    git_branch: str | None = None,
    mode: str | None = None,
    dashboard_url: str | None = None,
) -> dict[str, Any]:
    paths = _paths(state_dir)
    metadata = _read_metadata(paths["metadata"])
    exists = paths["markdown"].is_file()
    return _status_payload(
        state_dir=state_dir,
        paths=paths,
        project=project,
        cwd=cwd,
        git_root=git_root,
        git_branch=git_branch,
        mode=mode,
        dashboard_url=dashboard_url,
        exists=exists,
        metadata=metadata,
    )


def ensure_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    git_root: Path | None = None,
    git_branch: str | None = None,
    mode: str | None = None,
    dashboard_url: str | None = None,
) -> dict[str, Any]:
    paths = _paths(state_dir)
    metadata = _read_metadata(paths["metadata"])
    if not paths["markdown"].is_file():
        now = _now()
        paths["dir"].mkdir(parents=True, exist_ok=True)
        paths["markdown"].write_text(
            _initial_runbook(
                project=project,
                state_dir=state_dir,
                cwd=cwd,
                git_root=git_root,
                git_branch=git_branch,
                mode=mode,
                dashboard_url=dashboard_url,
                created_at=now,
            ),
            encoding="utf-8",
        )
        metadata = {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "title": f"WorkerBee Project Runbook - {project}",
            "project": project,
            "created_at": now,
            "updated_at": now,
            "source": "workerbee-session",
            "summary": "Initial project runbook generated by WorkerBee.",
            "repo_path": None,
            "history_count": 0,
        }
        _write_metadata(paths["metadata"], metadata)
    elif not metadata:
        now = _now()
        metadata = {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "title": f"WorkerBee Project Runbook - {project}",
            "project": project,
            "created_at": now,
            "updated_at": now,
            "source": "workerbee-session",
            "summary": "Recovered metadata for an existing project runbook.",
            "repo_path": None,
            "history_count": 0,
        }
        _write_metadata(paths["metadata"], metadata)

    return _status_payload(
        state_dir=state_dir,
        paths=paths,
        project=project,
        cwd=cwd,
        git_root=git_root,
        git_branch=git_branch,
        mode=mode,
        dashboard_url=dashboard_url,
        exists=True,
        metadata=metadata,
    )


def update_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    content: str,
    mode: str = "append",
    source: str = "agent",
    summary: str | None = None,
    git_root: Path | None = None,
    git_branch: str | None = None,
) -> dict[str, Any]:
    selected_mode = _normalize_update_mode(mode)
    update = content.strip()
    if not update:
        raise WorkerBeeError(
            code="EMPTY_RUNBOOK_UPDATE",
            message="runbook update content is empty",
            remediation="Pass non-empty markdown content.",
        )

    paths = _paths(state_dir)
    before_exists = paths["markdown"].is_file()
    if before_exists:
        _snapshot(paths)
    paths["dir"].mkdir(parents=True, exist_ok=True)
    now = _now()

    if selected_mode == "replace":
        new_text = f"{update}\n"
    else:
        if not before_exists:
            ensure_project_runbook(
                state_dir=state_dir,
                project=project,
                cwd=cwd,
                git_root=git_root,
                git_branch=git_branch,
            )
        current = paths["markdown"].read_text(encoding="utf-8").rstrip()
        summary_line = f"\nSummary: {summary.strip()}" if summary and summary.strip() else ""
        new_text = (
            f"{current}\n\n"
            f"## Update - {now}\n\n"
            f"Source: `{_safe_source(source)}`{summary_line}\n\n"
            f"{update}\n"
        )
    paths["markdown"].write_text(new_text, encoding="utf-8")

    metadata = _read_metadata(paths["metadata"])
    if not metadata:
        metadata = {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "title": f"WorkerBee Project Runbook - {project}",
            "project": project,
            "created_at": now,
            "repo_path": None,
            "history_count": 0,
        }
    metadata.update(
        {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "project": project,
            "updated_at": now,
            "source": _safe_source(source),
            "summary": summary.strip() if summary and summary.strip() else None,
            "history_count": len(list(paths["history"].glob("project-runbook-*.md"))),
        }
    )
    _write_metadata(paths["metadata"], metadata)
    return {
        **project_runbook_status(
            state_dir=state_dir,
            project=project,
            cwd=cwd,
            git_root=git_root,
            git_branch=git_branch,
        ),
        "changed": True,
        "mode": selected_mode,
    }


def export_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    path: str | Path = DEFAULT_REPO_RUNBOOK_PATH,
    overwrite: bool = False,
    git_root: Path | None = None,
    git_branch: str | None = None,
) -> dict[str, Any]:
    ensure_project_runbook(
        state_dir=state_dir,
        project=project,
        cwd=cwd,
        git_root=git_root,
        git_branch=git_branch,
    )
    paths = _paths(state_dir)
    destination = _resolve_repo_path(path=path, cwd=cwd, git_root=git_root)
    if destination.exists() and not overwrite:
        raise WorkerBeeError(
            code="RUNBOOK_EXPORT_EXISTS",
            message=f"runbook export path already exists: {destination}",
            details={"path": str(destination), "overwrite": overwrite},
            remediation="Pass overwrite=true or choose another repo-relative path.",
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(paths["markdown"], destination)
    metadata = _read_metadata(paths["metadata"])
    metadata.update(
        {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "project": project,
            "repo_path": _relative_to_base(destination, cwd=cwd, git_root=git_root),
            "updated_at": _now(),
            "source": "repo-export",
        }
    )
    _write_metadata(paths["metadata"], metadata)
    return {
        **project_runbook_status(
            state_dir=state_dir,
            project=project,
            cwd=cwd,
            git_root=git_root,
            git_branch=git_branch,
        ),
        "changed": True,
        "export_path": str(destination),
        "overwrite": overwrite,
    }


def import_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    path: str | Path = DEFAULT_REPO_RUNBOOK_PATH,
    mode: str = "replace",
    git_root: Path | None = None,
    git_branch: str | None = None,
) -> dict[str, Any]:
    selected_mode = _normalize_update_mode(mode)
    source_path = _resolve_repo_path(path=path, cwd=cwd, git_root=git_root)
    if not source_path.is_file():
        raise WorkerBeeError(
            code="RUNBOOK_IMPORT_NOT_FOUND",
            message=f"runbook import path does not exist: {source_path}",
            details={"path": str(source_path)},
            remediation="Export a runbook first or pass an existing repo-relative markdown path.",
        )
    result = update_project_runbook(
        state_dir=state_dir,
        project=project,
        cwd=cwd,
        content=source_path.read_text(encoding="utf-8"),
        mode=selected_mode,
        source="repo-import",
        summary=f"Imported from {_relative_to_base(source_path, cwd=cwd, git_root=git_root)}",
        git_root=git_root,
        git_branch=git_branch,
    )
    paths = _paths(state_dir)
    metadata = _read_metadata(paths["metadata"])
    metadata.update(
        {
            "repo_path": _relative_to_base(source_path, cwd=cwd, git_root=git_root),
            "source": "repo-import",
            "updated_at": _now(),
        }
    )
    _write_metadata(paths["metadata"], metadata)
    return {
        **result,
        "import_path": str(source_path),
    }


def _paths(state_dir: Path) -> dict[str, Path]:
    root = state_dir / "artifacts" / "runbooks"
    return {
        "dir": root,
        "markdown": root / "project-runbook.md",
        "metadata": root / "project-runbook.json",
        "history": root / "history",
    }


def _status_payload(
    *,
    state_dir: Path,
    paths: dict[str, Path],
    project: str,
    cwd: Path,
    git_root: Path | None,
    git_branch: str | None,
    mode: str | None,
    dashboard_url: str | None,
    exists: bool,
    metadata: dict[str, Any],
) -> dict[str, Any]:
    repo_path = metadata.get("repo_path") if isinstance(metadata.get("repo_path"), str) else None
    repo_file = None
    if repo_path:
        try:
            repo_file = _resolve_repo_path(path=repo_path, cwd=cwd, git_root=git_root)
        except WorkerBeeError:
            repo_file = None
    return {
        "api_version": PROJECT_RUNBOOK_API_VERSION,
        "project": project,
        "exists": exists,
        "title": metadata.get("title") or f"WorkerBee Project Runbook - {project}",
        "path": str(paths["markdown"]),
        "markdown_path": str(paths["markdown"]),
        "metadata_path": str(paths["metadata"]),
        "history_dir": str(paths["history"]),
        "state_dir": str(state_dir),
        "cwd": str(cwd),
        "git_root": str(git_root) if git_root else None,
        "git_branch": git_branch,
        "mode": mode,
        "dashboard_url": dashboard_url,
        "created_at": metadata.get("created_at"),
        "updated_at": metadata.get("updated_at"),
        "source": metadata.get("source"),
        "summary": metadata.get("summary"),
        "repo_path": repo_path,
        "repo_exists": bool(repo_file and repo_file.is_file()),
        "recommended_repo_path": DEFAULT_REPO_RUNBOOK_PATH,
        "history_count": int(metadata.get("history_count") or 0),
    }


def _initial_runbook(
    *,
    project: str,
    state_dir: Path,
    cwd: Path,
    git_root: Path | None,
    git_branch: str | None,
    mode: str | None,
    dashboard_url: str | None,
    created_at: str,
) -> str:
    dashboard = dashboard_url or "not running yet"
    return f"""# WorkerBee Project Runbook - {project}

Generated: {created_at}
Project: `{project}`
State Dir: `{state_dir}`
CWD: `{cwd}`
Git Root: `{git_root or "n/a"}`
Git Branch: `{git_branch or "n/a"}`
Mode: `{mode or "unknown"}`
Dashboard: {dashboard}

## Start / Stop / Restart

- Start from an agent session with `workerbee_v1_session_start` and use the returned project.
- Respect the project mode before starting workloads. Lazy mode should wait until deploy or
  explicit start is needed.
- Use `workerbee_v1_project_status` before runtime repairs so the current stack state is visible.

## Deploy / Validate

- Prefer checked-in manifests, Containerfiles, and project scripts before creating temporary
  WorkerBee artifacts.
- Build local images, validate staged manifests, deploy locally, inspect status/logs, and probe
  ingress before marking the stack ready.
- Keep first-run generated artifacts in WorkerBee state unless a human asks to persist them.

## Security / Review

- Keep secrets out of this runbook. Reference secret managers, SOPS paths, or evidence files
  without pasting secret values.
- Run project status before security review. If no deployment metadata exists, deploy or pass an
  explicit stage before reviewing.
- Summarize critical and high findings before lower-severity notes.

## Known Caveats

- Add project-specific runtime, ingress, data, migration, and teardown notes here after they are
  proven in a WorkerBee run.

## Update Policy

- After a successful bring-up, deploy, repair, or security review, append the reproducible steps
  with `workerbee_v1_project_runbook_update`.
- When this runbook is ready to persist in the repo, export it to
  `{DEFAULT_REPO_RUNBOOK_PATH}` with explicit overwrite approval.
"""


def _read_metadata(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _write_metadata(path: Path, metadata: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _snapshot(paths: dict[str, Path]) -> None:
    source = paths["markdown"]
    if not source.is_file():
        return
    paths["history"].mkdir(parents=True, exist_ok=True)
    target = paths["history"] / f"project-runbook-{_snapshot_stamp()}.md"
    counter = 1
    while target.exists():
        target = paths["history"] / f"project-runbook-{_snapshot_stamp()}-{counter}.md"
        counter += 1
    shutil.copyfile(source, target)


def _normalize_update_mode(mode: str) -> str:
    value = str(mode or "append").strip().lower()
    if value not in RUNBOOK_UPDATE_MODES:
        raise WorkerBeeError(
            code="INVALID_RUNBOOK_MODE",
            message="runbook mode must be append or replace",
            details={"mode": mode, "allowed": sorted(RUNBOOK_UPDATE_MODES)},
            remediation="Use mode='append' or mode='replace'.",
        )
    return value


def _resolve_repo_path(*, path: str | Path, cwd: Path, git_root: Path | None) -> Path:
    raw = Path(path).expanduser()
    if raw.is_absolute():
        raise WorkerBeeError(
            code="RUNBOOK_PATH_OUTSIDE_REPO",
            message="runbook import/export path must be repo-relative",
            details={"path": str(path)},
            remediation="Pass a repo-relative path such as docs/workerbee-runbook.md.",
        )
    base = (git_root or cwd).expanduser().resolve()
    resolved = (base / raw).resolve()
    try:
        resolved.relative_to(base)
    except ValueError as exc:
        raise WorkerBeeError(
            code="RUNBOOK_PATH_OUTSIDE_REPO",
            message="runbook import/export path escapes the project checkout",
            details={"path": str(path), "base": str(base)},
            remediation="Pass a path inside the project checkout.",
        ) from exc
    return resolved


def _relative_to_base(path: Path, *, cwd: Path, git_root: Path | None) -> str:
    base = (git_root or cwd).expanduser().resolve()
    try:
        return str(path.resolve().relative_to(base))
    except ValueError:
        return str(path.resolve())


def _safe_source(source: str) -> str:
    value = str(source or "agent").strip() or "agent"
    return value[:80]


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _snapshot_stamp() -> str:
    return time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
