"""Project-scoped WorkerBee runbook artifact helpers."""

from __future__ import annotations

import json
import re
import shutil
import time
from pathlib import Path
from typing import Any

from workerbee.contract import WorkerBeeError

PROJECT_RUNBOOK_API_VERSION = "workerbee.project-runbook/v1"
DEFAULT_REPO_RUNBOOK_PATH = "docs/workerbee-runbook.md"
RUNBOOK_UPDATE_MODES = {"append", "replace"}
RUNBOOK_SOURCE_MAX_LENGTH = 48
RUNBOOK_SUMMARY_MAX_LENGTH = 240
RUNBOOK_SECRET_VALUE_MIN_LENGTH = 8
RUNBOOK_SECRET_REFERENCE_PREFIXES = (
    "sops://",
    "vault://",
    "op://",
    "1password://",
    "aws-secretsmanager://",
    "gcp-secret-manager://",
    "azure-keyvault://",
)
RUNBOOK_SECRET_PLACEHOLDER_WORDS = (
    "changeme",
    "dummy",
    "example",
    "placeholder",
    "redacted",
    "replace-me",
    "test",
    "your-",
    "your_",
)
RUNBOOK_SECRET_MARKER_RE = re.compile(
    r"""(?ix)
    (?<![a-z0-9])
    (?P<marker>
        [a-z0-9_.-]*
        (?:
            api[_-]?key
            | client[_-]?secret
            | access[_-]?key
            | private[_-]?key
            | password
            | passwd
            | token
            | secret
        )
        [a-z0-9_.-]*
    )
    \s*[:=]\s*
    (?P<value>.+?)
    \s*$
    """
)
RUNBOOK_PRIVATE_KEY_RE = re.compile(r"-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----")


def project_runbook_status(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    git_root: Path | None = None,
    git_branch: str | None = None,
    mode: str | None = None,
    dashboard_url: str | None = None,
) -> dict[str, Any]:
    paths = _paths(state_dir)
    metadata = _read_metadata(paths["metadata"])
    exists = paths["markdown"].is_file()
    return _status_payload(
        state_dir=state_dir,
        paths=paths,
        project=project,
        cwd=cwd,
        git_root=git_root,
        git_branch=git_branch,
        mode=mode,
        dashboard_url=dashboard_url,
        exists=exists,
        metadata=metadata,
    )


def ensure_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    git_root: Path | None = None,
    git_branch: str | None = None,
    mode: str | None = None,
    dashboard_url: str | None = None,
) -> dict[str, Any]:
    paths = _paths(state_dir)
    metadata = _read_metadata(paths["metadata"])
    ensure_action = "existing"
    ensure_changed = False
    if not paths["markdown"].is_file():
        now = _now()
        paths["dir"].mkdir(parents=True, exist_ok=True)
        paths["markdown"].write_text(
            _initial_runbook(
                project=project,
                state_dir=state_dir,
                cwd=cwd,
                git_root=git_root,
                git_branch=git_branch,
                mode=mode,
                dashboard_url=dashboard_url,
                created_at=now,
            ),
            encoding="utf-8",
        )
        metadata = {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "title": f"WorkerBee Project Runbook - {project}",
            "project": project,
            "created_at": now,
            "updated_at": now,
            "source": "workerbee-session",
            "summary": "Initial project runbook generated by WorkerBee.",
            "repo_path": None,
            "history_count": 0,
        }
        _write_metadata(paths["metadata"], metadata)
        ensure_action = "created"
        ensure_changed = True
    elif not metadata:
        now = _now()
        metadata = {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "title": f"WorkerBee Project Runbook - {project}",
            "project": project,
            "created_at": now,
            "updated_at": now,
            "source": "workerbee-session",
            "summary": "Recovered metadata for an existing project runbook.",
            "repo_path": None,
            "history_count": 0,
        }
        _write_metadata(paths["metadata"], metadata)
        ensure_action = "metadata-recovered"
        ensure_changed = True

    return _status_payload(
        state_dir=state_dir,
        paths=paths,
        project=project,
        cwd=cwd,
        git_root=git_root,
        git_branch=git_branch,
        mode=mode,
        dashboard_url=dashboard_url,
        exists=True,
        metadata=metadata,
        ensure={
            "enabled": True,
            "changed": ensure_changed,
            "action": ensure_action,
        },
    )


def update_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    content: str,
    mode: str = "append",
    source: str = "agent",
    summary: str | None = None,
    git_root: Path | None = None,
    git_branch: str | None = None,
) -> dict[str, Any]:
    selected_mode = _normalize_update_mode(mode)
    update = content.strip()
    if not update:
        raise WorkerBeeError(
            code="EMPTY_RUNBOOK_UPDATE",
            message="runbook update content is empty",
            remediation="Pass non-empty markdown content.",
        )
    _raise_if_runbook_secrets(content=update, summary=summary)

    paths = _paths(state_dir)
    before_exists = paths["markdown"].is_file()
    if before_exists:
        _snapshot(paths)
    paths["dir"].mkdir(parents=True, exist_ok=True)
    now = _now()
    safe_source = _safe_source(source)
    safe_summary = _safe_summary(summary)

    if selected_mode == "replace":
        new_text = f"{update}\n"
    else:
        if not before_exists:
            ensure_project_runbook(
                state_dir=state_dir,
                project=project,
                cwd=cwd,
                git_root=git_root,
                git_branch=git_branch,
            )
        current = paths["markdown"].read_text(encoding="utf-8").rstrip()
        metadata_lines = f"Source: `{safe_source}`\n"
        if safe_summary:
            metadata_lines = f"{metadata_lines}Summary:\n> {safe_summary}\n"
        new_text = (
            f"{current}\n\n"
            f"## Update - {now}\n\n"
            f"{metadata_lines}\n"
            f"{update}\n"
        )
    paths["markdown"].write_text(new_text, encoding="utf-8")

    metadata = _read_metadata(paths["metadata"])
    if not metadata:
        metadata = {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "title": f"WorkerBee Project Runbook - {project}",
            "project": project,
            "created_at": now,
            "repo_path": None,
            "history_count": 0,
        }
    metadata.update(
        {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "project": project,
            "updated_at": now,
            "source": safe_source,
            "summary": safe_summary,
            "history_count": len(list(paths["history"].glob("project-runbook-*.md"))),
        }
    )
    _write_metadata(paths["metadata"], metadata)
    return {
        **project_runbook_status(
            state_dir=state_dir,
            project=project,
            cwd=cwd,
            git_root=git_root,
            git_branch=git_branch,
        ),
        "changed": True,
        "mode": selected_mode,
    }


def export_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    path: str | Path = DEFAULT_REPO_RUNBOOK_PATH,
    overwrite: bool = False,
    git_root: Path | None = None,
    git_branch: str | None = None,
) -> dict[str, Any]:
    ensure_project_runbook(
        state_dir=state_dir,
        project=project,
        cwd=cwd,
        git_root=git_root,
        git_branch=git_branch,
    )
    paths = _paths(state_dir)
    destination = _resolve_repo_path(path=path, cwd=cwd, git_root=git_root)
    if destination.exists() and not overwrite:
        raise WorkerBeeError(
            code="RUNBOOK_EXPORT_EXISTS",
            message=f"runbook export path already exists: {destination}",
            details={"path": str(destination), "overwrite": overwrite},
            remediation="Pass overwrite=true or choose another repo-relative path.",
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(paths["markdown"], destination)
    metadata = _read_metadata(paths["metadata"])
    metadata.update(
        {
            "api_version": PROJECT_RUNBOOK_API_VERSION,
            "project": project,
            "repo_path": _relative_to_base(destination, cwd=cwd, git_root=git_root),
            "updated_at": _now(),
            "source": "repo-export",
        }
    )
    _write_metadata(paths["metadata"], metadata)
    return {
        **project_runbook_status(
            state_dir=state_dir,
            project=project,
            cwd=cwd,
            git_root=git_root,
            git_branch=git_branch,
        ),
        "changed": True,
        "export_path": str(destination),
        "overwrite": overwrite,
    }


def import_project_runbook(
    *,
    state_dir: Path,
    project: str,
    cwd: Path,
    path: str | Path = DEFAULT_REPO_RUNBOOK_PATH,
    mode: str = "replace",
    git_root: Path | None = None,
    git_branch: str | None = None,
) -> dict[str, Any]:
    selected_mode = _normalize_update_mode(mode)
    source_path = _resolve_repo_path(path=path, cwd=cwd, git_root=git_root)
    if not source_path.is_file():
        raise WorkerBeeError(
            code="RUNBOOK_IMPORT_NOT_FOUND",
            message=f"runbook import path does not exist: {source_path}",
            details={"path": str(source_path)},
            remediation="Export a runbook first or pass an existing repo-relative markdown path.",
        )
    result = update_project_runbook(
        state_dir=state_dir,
        project=project,
        cwd=cwd,
        content=source_path.read_text(encoding="utf-8"),
        mode=selected_mode,
        source="repo-import",
        summary=f"Imported from {_relative_to_base(source_path, cwd=cwd, git_root=git_root)}",
        git_root=git_root,
        git_branch=git_branch,
    )
    paths = _paths(state_dir)
    metadata = _read_metadata(paths["metadata"])
    metadata.update(
        {
            "repo_path": _relative_to_base(source_path, cwd=cwd, git_root=git_root),
            "source": "repo-import",
            "updated_at": _now(),
        }
    )
    _write_metadata(paths["metadata"], metadata)
    return {
        **result,
        "import_path": str(source_path),
    }


def _paths(state_dir: Path) -> dict[str, Path]:
    root = state_dir / "artifacts" / "runbooks"
    return {
        "dir": root,
        "markdown": root / "project-runbook.md",
        "metadata": root / "project-runbook.json",
        "history": root / "history",
    }


def _status_payload(
    *,
    state_dir: Path,
    paths: dict[str, Path],
    project: str,
    cwd: Path,
    git_root: Path | None,
    git_branch: str | None,
    mode: str | None,
    dashboard_url: str | None,
    exists: bool,
    metadata: dict[str, Any],
    ensure: dict[str, Any] | None = None,
) -> dict[str, Any]:
    repo_path = metadata.get("repo_path") if isinstance(metadata.get("repo_path"), str) else None
    repo_file = None
    if repo_path:
        try:
            repo_file = _resolve_repo_path(path=repo_path, cwd=cwd, git_root=git_root)
        except WorkerBeeError:
            repo_file = None
    return {
        "api_version": PROJECT_RUNBOOK_API_VERSION,
        "project": project,
        "exists": exists,
        "title": metadata.get("title") or f"WorkerBee Project Runbook - {project}",
        "path": str(paths["markdown"]),
        "markdown_path": str(paths["markdown"]),
        "metadata_path": str(paths["metadata"]),
        "history_dir": str(paths["history"]),
        "state_dir": str(state_dir),
        "cwd": str(cwd),
        "git_root": str(git_root) if git_root else None,
        "git_branch": git_branch,
        "mode": mode,
        "dashboard_url": dashboard_url,
        "created_at": metadata.get("created_at"),
        "updated_at": metadata.get("updated_at"),
        "source": metadata.get("source"),
        "summary": metadata.get("summary"),
        "repo_path": repo_path,
        "repo_exists": bool(repo_file and repo_file.is_file()),
        "recommended_repo_path": DEFAULT_REPO_RUNBOOK_PATH,
        "history_count": int(metadata.get("history_count") or 0),
        "ensure": ensure
        or {
            "enabled": False,
            "changed": False,
            "action": "status-only",
        },
    }


def _initial_runbook(
    *,
    project: str,
    state_dir: Path,
    cwd: Path,
    git_root: Path | None,
    git_branch: str | None,
    mode: str | None,
    dashboard_url: str | None,
    created_at: str,
) -> str:
    dashboard = dashboard_url or "not running yet"
    return f"""# WorkerBee Project Runbook - {project}

Generated: {created_at}
Project: `{project}`
State Dir: `{state_dir}`
CWD: `{cwd}`
Git Root: `{git_root or "n/a"}`
Git Branch: `{git_branch or "n/a"}`
Mode: `{mode or "unknown"}`
Dashboard: {dashboard}

## Start / Stop / Restart

- Start from an agent session with `workerbee_v1_session_start` and use the returned project.
- Respect the project mode before starting workloads. Lazy mode should wait until deploy or
  explicit start is needed.
- Use `workerbee_v1_project_status` before runtime repairs so the current stack state is visible.

## Deploy / Validate

- Prefer checked-in manifests, Containerfiles, and project scripts before creating temporary
  WorkerBee artifacts.
- Build local images, validate staged manifests, deploy locally, inspect status/logs, and probe
  ingress before marking the stack ready.
- Use `hardening_profile="hardened"` for WorkerBee-generated or deliberately minimal images. Leave
  arbitrary repo Dockerfiles on the standard advisory profile unless a hardening change is in scope.
- Generated native k1s manifests include non-root, seccomp, capability-drop, and read-only root
  filesystem defaults; loosen them only when runtime validation proves the app needs writes.
- Keep first-run generated artifacts in WorkerBee state unless a human asks to persist them.

## Teardown / Cleanup

- For k1s profile work, verify `workerbee_v1_capabilities` reports
  `runtime.selected == containerd` before profile start, stop, purge, or profile-target deploy.
- Stop profile workloads with `workerbee_v1_profile_stop(purge=true)` after evidence or validation
  when the profile is not intended to stay running.
- If profile cleanup reports `K1S_PROFILE_REQUIRES_CONTAINERD`, restart or select WorkerBee with
  `--runtime containerd --containerd-privilege sudo-helper`, then retry the profile stop/purge.
- Keep fallback cleanup scoped to WorkerBee state-hash namespaces and state-local data roots. Do not
  prune reserved namespaces such as `ae`, `k8s.io`, `moby`, or `default`.

## Security / Review

- Keep secrets out of this runbook. Reference secret managers, SOPS paths, or evidence files
  without pasting secret values.
- Run project status before security review. If no deployment metadata exists, deploy or pass an
  explicit stage before reviewing.
- Review image build hardening metadata and manifest security findings before widening permissions
  or base images.
- Summarize critical and high findings before lower-severity notes.

## Known Caveats

- Add project-specific runtime, ingress, data, migration, and teardown notes here after they are
  proven in a WorkerBee run.

## Update Policy

- Public session and runbook status calls may create or recover this state-local runbook. Inspect
  the returned `ensure.action` field to distinguish `created`, `metadata-recovered`, `existing`,
  and read-only helper `status-only` results.
- After a successful bring-up, deploy, repair, or security review, append the reproducible steps
  with `workerbee_v1_project_runbook_update`.
- Runbook updates and imports reject high-confidence secret assignments and private key blocks.
  Use redacted placeholders such as `TOKEN=***` or references to secret managers instead.
- Update `source` and `summary` metadata are normalized before storage so appended sections remain
  single-line and Markdown-safe.
- When this runbook is ready to persist in the repo, export it to
  `{DEFAULT_REPO_RUNBOOK_PATH}` with explicit overwrite approval.
"""


def _read_metadata(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _write_metadata(path: Path, metadata: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _snapshot(paths: dict[str, Path]) -> None:
    source = paths["markdown"]
    if not source.is_file():
        return
    paths["history"].mkdir(parents=True, exist_ok=True)
    target = paths["history"] / f"project-runbook-{_snapshot_stamp()}.md"
    counter = 1
    while target.exists():
        target = paths["history"] / f"project-runbook-{_snapshot_stamp()}-{counter}.md"
        counter += 1
    shutil.copyfile(source, target)


def _normalize_update_mode(mode: str) -> str:
    value = str(mode or "append").strip().lower()
    if value not in RUNBOOK_UPDATE_MODES:
        raise WorkerBeeError(
            code="INVALID_RUNBOOK_MODE",
            message="runbook mode must be append or replace",
            details={"mode": mode, "allowed": sorted(RUNBOOK_UPDATE_MODES)},
            remediation="Use mode='append' or mode='replace'.",
        )
    return value


def _resolve_repo_path(*, path: str | Path, cwd: Path, git_root: Path | None) -> Path:
    raw = Path(path).expanduser()
    if raw.is_absolute():
        raise WorkerBeeError(
            code="RUNBOOK_PATH_OUTSIDE_REPO",
            message="runbook import/export path must be repo-relative",
            details={"path": str(path)},
            remediation="Pass a repo-relative path such as docs/workerbee-runbook.md.",
        )
    base = (git_root or cwd).expanduser().resolve()
    resolved = (base / raw).resolve()
    try:
        resolved.relative_to(base)
    except ValueError as exc:
        raise WorkerBeeError(
            code="RUNBOOK_PATH_OUTSIDE_REPO",
            message="runbook import/export path escapes the project checkout",
            details={"path": str(path), "base": str(base)},
            remediation="Pass a path inside the project checkout.",
        ) from exc
    return resolved


def _relative_to_base(path: Path, *, cwd: Path, git_root: Path | None) -> str:
    base = (git_root or cwd).expanduser().resolve()
    try:
        return str(path.resolve().relative_to(base))
    except ValueError:
        return str(path.resolve())


def _safe_source(source: str) -> str:
    value = str(source or "agent").strip().lower()
    value = re.sub(r"[^a-z0-9_.:-]+", "-", value).strip("-._:")
    if not value:
        value = "agent"
    return value[:RUNBOOK_SOURCE_MAX_LENGTH].rstrip("-._:") or "agent"


def _safe_summary(summary: str | None) -> str | None:
    value = str(summary or "").strip()
    if not value:
        return None
    value = value.replace("`", "'")
    value = re.sub(r"\s+", " ", value).strip()
    value = value.lstrip("#>-*+ ")
    if not value:
        return None
    if len(value) > RUNBOOK_SUMMARY_MAX_LENGTH:
        value = f"{value[: RUNBOOK_SUMMARY_MAX_LENGTH - 3].rstrip()}..."
    return value


def _raise_if_runbook_secrets(*, content: str, summary: str | None) -> None:
    findings = [
        *_runbook_secret_findings(content, field="content"),
        *_runbook_secret_findings(summary or "", field="summary"),
    ]
    if not findings:
        return
    raise WorkerBeeError(
        code="RUNBOOK_SECRET_DETECTED",
        message="runbook update appears to contain a secret value",
        details={"findings": findings},
        remediation=(
            "Remove secret values before updating the runbook. Use redacted placeholders such as "
            "`TOKEN=***` or references to secret managers instead."
        ),
    )


def _runbook_secret_findings(value: str, *, field: str) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for line_number, line in enumerate(value.splitlines(), start=1):
        if RUNBOOK_PRIVATE_KEY_RE.search(line):
            findings.append(
                {
                    "field": field,
                    "line": line_number,
                    "marker": "private_key",
                }
            )
        marker_match = RUNBOOK_SECRET_MARKER_RE.search(line)
        if not marker_match:
            continue
        marker = _secret_marker(marker_match.group("marker"))
        secret_value = _strip_secret_value(marker_match.group("value"))
        if _runbook_secret_value_is_placeholder(secret_value):
            continue
        findings.append(
            {
                "field": field,
                "line": line_number,
                "marker": marker,
            }
        )
    return findings


def _secret_marker(value: str) -> str:
    marker = value.lower().replace("-", "_").replace(".", "_")
    if "api_key" in marker:
        return "api_key"
    if "client_secret" in marker:
        return "client_secret"
    if "access_key" in marker:
        return "access_key"
    if "private_key" in marker:
        return "private_key"
    if "password" in marker or "passwd" in marker:
        return "password"
    if "token" in marker:
        return "token"
    return "secret"


def _strip_secret_value(value: str) -> str:
    stripped = value.split("#", 1)[0].strip().rstrip(",;")
    if len(stripped) >= 2 and stripped[0] == stripped[-1] and stripped[0] in {"'", '"'}:
        stripped = stripped[1:-1].strip()
    return stripped


def _runbook_secret_value_is_placeholder(value: str) -> bool:
    if not value:
        return True
    lowered = value.lower()
    if len(value) < RUNBOOK_SECRET_VALUE_MIN_LENGTH:
        return True
    if any(lowered.startswith(prefix) for prefix in RUNBOOK_SECRET_REFERENCE_PREFIXES):
        return True
    if re.fullmatch(r"[*xX]+", value):
        return True
    if re.fullmatch(r"<[^>\s]+>", value):
        return True
    if re.fullmatch(r"\$[A-Za-z_][A-Za-z0-9_]*", value):
        return True
    if re.fullmatch(r"\$\{[^}]+\}", value):
        return True
    if re.fullmatch(r"\$\([^)]+\)", value):
        return True
    if re.fullmatch(r"\{\{[^}]+\}\}", value):
        return True
    if any(word in lowered for word in RUNBOOK_SECRET_PLACEHOLDER_WORDS):
        return True
    # Keep this guard high-confidence: explanatory prose is not treated as a leaked secret.
    return bool(re.search(r"\s", value))


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _snapshot_stamp() -> str:
    return time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
